### PR TITLE
(Fix/staff list) Mobile pagination

### PR DESCRIPTION
**Pull request by zamurvedovattosymplicity**
A mobile pagination was made based on the layout: https://christianboyle.com/ss/2021-10-21_11-55-41AM.png

To accomplish it, classes from this bootstrap example (https://getbootstrap.com/docs/5.1/examples/sticky-footer/) were used (position-sticky, mt-auto and bottom-0).

### CODE REVIEW

**Comment by christianboyle** [comment]
Looking good, just a few things:

2021-11-08_10-30-25AM

1. Remove space between bottom scrollbar and footer
2. Make footer background gray instead of white
3. Change `Show 20` control to be a count `1-20 of 140`
4. Darken borders on pagination controls so they stand out more when you have a gray background

You might consider having 2 footers in the markup and only showing them based on classes like https://getbootstrap.com/docs/5.1/utilities/display/#hiding-elements

**Comment by zamurvedovattosymplicity** [comment]
@christianboyle please, take a look at changes based on your requests.

**Comment by christianboyle** [comment]
Looking good! Just a couple of small changes to the classes on the `select` elements to retain their focus style:

`<select class="form-select lh-sm fs-6 bg-transparent border-light" aria-label="Default select example">`

and

`<select class="form-select fs-6 ps-3 pe-9 h-100 lh-sm rounded-0 page-link text-secondary m-0 border-dark" aria-label="Default select example">`

**Comment by christianboyle** [comment]
LGTM

**Pull request merged**
